import product1 from "../assets/products/1.jpg";
import product2 from "../assets/products/2.jpg";

export const products = [
  {
    id: 1,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 2,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 3,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 4,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 5,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 6,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 7,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 8,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 9,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 10,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 11,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 12,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 13,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 14,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 15,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product1,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
  {
    id: 16,
    category: "Watch",
    name: "Makura Watch",
    description:
      "A fully automatic watch with a stainless steel body and a leather strap.",
    productPrice: "20000",
    discount: "10",
    image: product2,
    sliderImages: [
      {
        id: 1,
        image: product1,
        title: "Makura Watch",
      },
      {
        id: 2,
        image: product2,
        title: "Makura Watch",
      },
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
    material: "Stainless Steel",
    brand: "Makura",
    rating: 4.5,
    availableStock: 120,
    sku: "TSH12345",
    gender: "Unisex",
    warranty: "1 Year",
    withProduct: "Extra Strap",
  },
];
